# Generated by Django 3.2 on 2021-04-25 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="name",
            field=models.CharField(default="test-chat", max_length=50),
            preserve_default=False,
        ),
    ]
