# Generated by Django 3.2 on 2021-04-25 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="node",
            name="success_node",
        ),
        migrations.AddField(
            model_name="node",
            name="nodes",
            field=models.ManyToManyField(
                null=True, related_name="_nodes_node_nodes_+", to="nodes.Node"
            ),
        ),
        migrations.AlterField(
            model_name="node",
            name="fail_node",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fail_predecessor",
                to="nodes.node",
            ),
        ),
    ]
