# Generated by Django 3.2 on 2021-04-26 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='answer_type',
        ),
        migrations.AddField(
            model_name='node',
            name='answer_type',
            field=models.CharField(choices=[('general', 'General'), ('date', 'Date'), ('time', 'Time')], default='general', max_length=50),
            preserve_default=False,
        ),
    ]
