# Generated by Django 3.2 on 2021-04-25 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0002_auto_20210425_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='nodes',
            field=models.ManyToManyField(related_name='_nodes_node_nodes_+', to='nodes.Node'),
        ),
    ]
