# Generated by Django 3.2 on 2021-06-02 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0002_auto_20210426_1203"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="answer",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="node",
            name="fail_node",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fail_predecessor",
                to="nodes.node",
            ),
        ),
    ]
